# This makefile builds the sample for a POSIX system, like Linux

INC = -I$(ZEPHYR_BASE)/include

LIBPATH = $(ZEPHYR_BASE)/subsys/net/lib/zstream

LIBSRC = \
    $(LIBPATH)/zstream_sock.c \
    $(LIBPATH)/zstream_tls.c \

LDLIBS = -lmbedtls -lmbedx509 -lmbedcrypto

http_get: src/http_get.c
	$(CC) $(INC) $(CFLAGS) $^ $(LIBSRC) $(LDLIBS) -o $@
